config/routes.rb
SuitRiot::Application.routes.draw do
  
  root :to => 'images#index'
  
  resource :user_session
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "profile" => "users#show"
  
  resource :account, :controller => "users"
  resources :users
  
  resources :images
  match "submit" => "images#new"
  
  resources :votes
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :votes,  :dependent => :destroy
  
  def self.random
    current_user_session = UserSession.find
    @current_user = current_user_session && current_user_session.user
    if @current_user
      ids = connection.select_all("SELECT id FROM images WHERE user_id != #{@current_user.id}")
    else
      ids = connection.select_all("SELECT id FROM images")
    end
    find(ids[rand(ids.length)]["id"].to_i) unless ids.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.maintain_sessions = false
  end
  
  has_many :images, :dependent => :destroy
  has_many :votes,  :dependent => :destroy
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
  
  def previous_score_for(vote_category)
    (self.send("#{vote_category}_score")).to_int
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  require 'authlogic'

  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end
    
    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end

    def store_location
      session[:return_to] = request.request_uri
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :require_user, :only => [:new, :create, :edit, :update]
  
  @@BUCKET = "suitriot"
  
  def index
    @images = Image.order(:created_at).limit(12)
  end
  
  def show
    @image = Image.find(params[:id])
    @user = current_user
    @image.votes.where(:user_id => @user).first.nil? ? @vote = Vote.new(:image => @image, :user => current_user)
                                                     : @vote = @image.votes.where(:user_id => @user).first
  end
  
  def new
    @user = @current_user
    @image = Image.new
  end
  
  def create
    fileUp = params[:upload]
    if fileUp['datafile'].size > 5.megabytes
      flash[:error] = "Maximum image size is 5 MB"
      redirect_to :action => :new
      return
    end
    orig_filename = fileUp['datafile'].original_filename
    filename = Digest::SHA1.hexdigest("#{Time.now.utc}--#{orig_filename}")
    filename = "#{filename}.png"
    AWS::S3::S3Object.store(filename, fileUp['datafile'].read, @@BUCKET, :access => :public_read)
    url = AWS::S3::S3Object.url_for(filename, @@BUCKET, :authenticated => false)
    @image = Image.new(params[:image])
    @image.user = current_user
    @image.filename = filename
    @image.url = url;
    if @image.save
      flash[:success] = "Image saved!"
      redirect_to :action => :show, :id => @image
    else
      flash[:error] = "ERROR: Unable to save the image that was provided."
      redirect_to :action => :new
    end
  end

  def destroy
    @image = Image.find(params[:id])
    AWS::S3::S3Object.find(@image.filename.to_s, @@BUCKET).delete
    @image.destroy
    redirect_to :account
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful. Welcome back, #{@user_session.user.login}."
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful."
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      UserSession.create @user
      flash[:notice] = "Account registered!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  def create    
    @vote = Vote.new(params[:vote])
    @vote.user = current_user unless current_user.nil?
    if @vote.save
      flash[:notice] = "Your vote has been saved."
    end
    redirect_back_or_default root_url
  end
  
  def update
    @vote = Vote.find(params[:id])
    @vote = Vote.update(params[:id], params[:vote])
    if @vote.update_attributes(params[:model])
      flash[:notice] = "Your vote has been saved."
    else
      flash[:error] = "There was a problem saving your vote."
    end
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include TweetButton
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/images/index.html.erb
<div class="row">
	<div class="span10 columns offset3">
		<% if current_user.nil? %>
		<div class="alert-message info">
			SuitRiot is a web app for sharing and voting on pictures of men's fashion. Create an account for free in order to share your own images and save your voting history.
		</div>
		<% end %>
	</div>
</div>
<div class="row">
	<div class="span16 columns">
			<ul class="polaroids">
				<% @images.each do |image| %>
					<li>
						<%= link_to image_tag(image.url), 				
												image_path(image.id), 
												:title => image.user.login %>
					</li>
				<% end %>
			</ul>
	</div>
</div>

app/views/images/new.html.erb
<%= form_for @image, :html => {:multipart => true, :accept => "image/gif,image/png,image/jpg"} do |f| %>

	<div class="clearfix">
		<h4>
			Please note: SuitRiot is for sharing images related to men's fashion. Unrelated or inappropriate images will be removed, and repeated uploading of such images will result in account deletion.
		
			Use the form below to select a JPEG, PNG, or GIF to upload. Maximum file size is 5 MB.
		</h4>
	</div>

	<% if flash[:error] %>
	<div class="alert-message error">
		<%= flash[:error] %>
	</div>
	<% end %>
	
 	<div class="clarfix" style="width: 400px;" >
   	<%= file_field 'upload', 'datafile' %>
 	</div>
	<p>
 	<div class="clearfix">
		<%= f.submit "Upload image", :class => "btn primary" %>
 	</div>

<% end %>

app/views/images/show.html.erb
<div class="row">
	<div class="span10 columns offset3">
		<% if current_user.nil? %>
		<div class="alert-message info">
			SuitRiot is a web app for sharing and voting on pictures of men's fashion. Create an account for free in order to share your own images and save your voting history.
		</div>
		<% end %>
	</div>
</div>
<div class="row">
	<div class="span10 columns">
		<center>
			<div class="well">
				<%= image_tag(@image.url, :style => 'max-height: 720px; max-width: 540px;') %>
			</div>
		</center>
		<div class="well">
			<div>
				Submitted by <b><%= @image.user.login %></b> <%= time_ago_in_words(@image.created_at) %> ago.<br />
				Rated <%= @image.votes.count %> times.
			</div>
			<%= render :partial => 'shared/score_block', :object => @image unless @image.votes.count < 1%>
		</div>
	</div>
	<div class="span6 columns">
		<div class="well">
			<div align=right>
				<%= tweet_button(:via => "suitriot", :text => "Like: #{@image.user.login}'s outfit", :count => "none") %>
			</div>
			<% if @image.user == current_user %>
				<h6>This Image is Yours</h6>
				<%= button_to("Delete Image", @image, :method => :delete, :class => 'btn danger', :confirm => 'Permanently delete this image?') %>
			<% else %>
				<h3>Judge this Outfit</h3>
				<div class="clearfix">
					<% @vote = Vote.new if @vote.nil? %>
					<%= form_for @vote do |f| %>
						<input id="image_id" name="vote[image_id]" type="hidden" value="<%= @image.id %>" />
						<%= render :partial => 'shared/voting_pane', :object => f %>
					<% end %>
				</div>
			<% end %>
		</div>
		<center>©2011 SuitRiot</center>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuitRiot</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= render :partial => 'shared/tabs' %>
<div class="container">
	<% if flash[:notice] %>
		<div class="alert-message success" data-alert="alert">
	  	<a class="close" href="#">&times;</a>
	  	<p><%= flash[:notice] %></p>
		</div>
 	<% end %>
	<% if flash[:error] %>
	  <p class="error"><%= flash[:error] %></p>
	<% end %>
	
	<%= yield %>
</div>

</body>
</html>

app/views/shared/_score_block.erb
<div id="score-block">
	<h6>Overall rating:</h6> <b><%= (score_block.votes.sum(:overall_score).to_f / score_block.votes.count.to_f * 100).to_i %>%</b> on <%= score_block.votes.count('overall_score') %> votes.
	<h6>Jacket/Shirt(s) rating:</h6> <b><%= (score_block.votes.sum(:tops_score).to_f / score_block.votes.count.to_f * 100).to_i %>%</b> on <%= score_block.votes.count('tops_score') %> votes.
	<h6>Pants rating:</h6> <b><%= (score_block.votes.sum(:pants_score).to_f / score_block.votes.count.to_f * 100).to_i %>%</b> on <%= score_block.votes.count('pants_score') %> votes.
	<h6>Shoes rating:</h6> <b><%= (score_block.votes.sum(:shoes_score).to_f / score_block.votes.count.to_f * 100).to_i %>%</b> on <%= score_block.votes.count('shoes_score') %> votes.
	<h6>Accessories rating:</h6> <b><%= (score_block.votes.sum(:accessories_score).to_f / score_block.votes.count.to_f * 100).to_i %>%</b> on <%= score_block.votes.count('accessories_score') %> votes.
</div>

app/views/shared/_tabs.erb
<div id="topbar" class="topbar-wrapper" style="z-index: 5;"> 
  <div class="topbar"> 
    <div class="topbar-inner"> 
      <div class="container"> 
        <h3><%= link_to 'Suit Riot', root_path %></h3>
				<ul class="nav">
					<li><%= link_to 'Latest Images', images_path %>
				</ul>
        <ul class="nav secondary-nav">
          <% if current_user %>
						<li><%= link_to current_user.login, account_path %></li>
						<li><%= link_to 'Upload', submit_path %></li>
						<li><%= link_to 'Log Out', logout_path, :method => :delete %></li>
					<% else %>
						<li><%= link_to 'Log In', login_path, :method => :new %></li>
						<li><a href="/users/new">Create Account</a></li>
					<% end %>
        </ul> 
      </div> 
    </div><!-- /topbar-inner --> 
  </div><!-- /topbar --> 
</div><!-- /topbar-wrapper -->

app/views/shared/_voting_pane.erb
<% if current_user %>
<h4>Overall</h4>
<div class="clearfix"> 
  <ul class="inputs-list"> 
    <li>
			<%= voting_pane.collection_radio :overall_score, 
																				[['1', 'Looking good!'], ['-1', 'Not a fan.']], 
																				:first, :last %>
    </li>
  </ul> 
</div><!-- /clearfix -->
<h4>Jacket + Shirt(s)</h4>
<div class="clearfix"> 
  <ul class="inputs-list"> 
    <li>
			<%= voting_pane.collection_radio :tops_score, 
																				[['1', 'Like'], ['-1', 'Dislike'], ['0', 'not pictured']], 
																				:first, :last %>
		</li>
  </ul> 
</div><!-- /clearfix -->
<h4>Pants</h4>
<div class="clearfix"> 
  <ul class="inputs-list"> 
    <li>
			<%= voting_pane.collection_radio :pants_score, 
																				[['1', 'Like'], ['-1', 'Dislike'], ['0', 'not pictured']], 
																				:first, :last %>
		</li>
  </ul> 
</div><!-- /clearfix -->
<h4>Shoes</h4>
<div class="clearfix"> 
  <ul class="inputs-list"> 
    <li>
			<%= voting_pane.collection_radio :shoes_score, 
																				[['1', 'Like'], ['-1', 'Dislike'], ['0', 'not pictured']], 
																				:first, :last %>
		</li>
  </ul> 
</div><!-- /clearfix -->
<h4>Accessories (watch/belt/etc.)</h4>
<div class="clearfix"> 
  <ul class="inputs-list"> 
    <li>
			<%= voting_pane.collection_radio :accessories_score, 
																				[['1', 'Like'], ['-1', 'Dislike'], ['0', 'not pictured']], 
																				:first, :last %>
		</li>
  </ul> 
</div><!-- /clearfix -->
<center><%= voting_pane.submit "Submit",	:class => 'btn large primary' %></center>
<% else %>
<%= link_to 'Log in', login_path %> or <%= link_to 'Create an Account', new_account_path %> in order to vote on images
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_for @user_session, :url => user_session_path do |f| %>
  <%= f.error_messages %>
	<div class="clearfix">
  	<%= f.label :login %>
		<div class="input">
  		<%= f.text_field :login %>
		</div>
  </div>
	<div class="clearfix">
  	<%= f.label :password %>
		<div class="input">
  		<%= f.password_field :password %>
		</div>
	</div>
	<div class="clearfix">
		<div class="input">
			<ul class="inputs-list"> 
		    <li> 
		      <label> 
		        <%= f.check_box :remember_me %> Remember me
		      </label> 
		    </li>
			</ul>
		</div>
	</div>
  <%= f.submit "Login", :class => 'btn large primary' %>
<% end %>

app/views/users/_form.erb
<div class='clearfix'>
	<%= form.label :login %>
	<div class='input'>
		<%= form.text_field :login %>
	</div>
</div>
<div class='clearfix'>
	<%= form.label :email %>
	<div class='input'>
		<%= form.text_field :email %>
	</div>
</div>
<div class='clearfix'>
	<%= form.label :password, form.object.new_record? ? nil : "Change password" %>
	<div class='input'>
		<%= form.password_field :password %>
	</div>
</div>
<div class='clearfix'>
	<%= form.label :password_confirmation %>
	<div class='input'>
		<%= form.password_field :password_confirmation %>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Edit My Account</h1>

<%= form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update", :class => 'btn large primary' %>
<% end %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Register", :class => 'btn large primary' %>
<% end %>

app/views/users/show.html.erb
<div class="row">
	<div class="span12 columns">
		<div class="well">
			<h6>My Images <%= link_to "+", new_image_path %></h6>
			<% @user.images.reverse.each do |image| %>
				<%= link_to image_tag(image.url, :style => 'max-height: 100px; width: 100px;'), image %>
			<% end %>
		</div>
	</div>
	<div class="span4 columns">
		<div class="well" align=right>
			<%= link_to 'Manage Account', edit_account_path %>
		</div>
	</div>
</div>